### ISSUE TITLE
Icon can be very pixelated with alternative launcher

### ISSUE THREAD

**Issue by Porkepix** [Perflyst/Twire#100]
Using OpenLauncher (https://github.com/OpenLauncherTeam/openlauncher/) as an alternative launcher, I could notice that in tha app drawer, Twire's icon is very pixelated. This is the only one to be pixelated like that, but it's not pixelated with the default Pixel launcher.

See the joined screenshot below

![Screenshot_20200605-175426](https://user-images.githubusercontent.com/709500/83897795-59922f00-a756-11ea-97a6-bee711fbf1ad.png)

Problem can come from the launcher, but considering Twire is the only one to be affected, I thought about opening the issue here. I'm not an Android developer to confirm where does it come from.

**Comment by MF-Debug** [comment]
i don't know if my issue is related to this, i am using stock lineageos launcher & twire icon looks like this
![Screenshot_20200612-190847_Trebuchet](https://user-images.githubusercontent.com/6173607/84507038-0bdf6e80-ace2-11ea-9626-0a3b83750d19.png)

But in settings, the app icon looks like this
![Screenshot_20200611-004044_Settings](https://user-images.githubusercontent.com/6173607/84507101-20236b80-ace2-11ea-8d28-7a405e56fa74.png)

also in the app's setting, it looks pixelated as well
![Screenshot_20200611-004101_Settings](https://user-images.githubusercontent.com/6173607/84507181-3e896700-ace2-11ea-85b0-d74e6ccd70a8.png)

I am using official lineageos 16.0 on galaxy note 3 SM-N9005.
