### ISSUE TITLE
[Bug] Followed streamers list is empty

### ISSUE THREAD

**Issue by bennyhillthebest** [Perflyst/Twire#101]
Logged into my account with a fresh installation of the app. Online streamers are shown with no issue, but the complete followed streamers list is empty and when pulling down to force refresh it the app crashes.

Thank you very much for this amazing fork, i hope low latency is going to be implemented, without it it's really difficult to watch streams.

**Comment by samfundev** [comment]
I believe this was fixed in dc7a7d0c6cee84dfe9d3444e3aa1d13cd01c58ad, let me know if you're still having this issue.
