### ISSUE TITLE
Icon replaced with generic android icon after recent update

### ISSUE THREAD

**Issue by shom13** [Perflyst/Twire#110]
Just to bring to your notice, the icon that used appear, has now been replaced with an android generic icon, after recent update

**Comment by samfundev** [comment]
What version of Android are you using?

**Comment by shom13** [comment]
Android 7

**Comment by nuttenpreller** [comment]
Same problem here
Android 5.1.1
![Screenshot_2020-07-23-17-33-26](https://user-images.githubusercontent.com/67310926/88306174-b055c700-cd0a-11ea-91d2-a13d379fe4fd.png)
