### ISSUE TITLE
Translations?

### ISSUE THREAD

**Issue by RAMAR-RAR** [Perflyst/Twire#22]
There is a plan for translations or not?
Because I want translate the app.

@ApoRes1337 [https://github.com/Perflyst/Twire/issues/9](url)

**Comment by Perflyst** [comment]
Done with 92dafd805ba6bbfc55a0fcb92d2745f7350fa7c9

For another language you need to create a folder under `/app/src/main/res/values-<LANGUAGE-CODE>` and copy the strings.xml file from `/app/src/main/res/values` into the newly created folder. There you can translate the strings than.
