### ISSUE TITLE
Italian Translation

### ISSUE THREAD

**Issue by RAMAR-RAR** [Perflyst/Twire#23]
I haven't the permission to upload the xml file but I attached it in this link (https://jirafeau.net/f.php?h=2vxj_1Iq&d=1)

**Comment by Perflyst** [comment]
Normally you fork the project and than you have permissions to push. Anyway, thank you. I will add it to the app

If the update is published and your phones language is set to italian, than the app should be in italian.

**Comment by Perflyst** [comment]
Added in d1bd31c93677d025a562c72939d2eee76a3f0729
