### ISSUE TITLE
Allow to use "previous" button to return from a stream to the main menus

### ISSUE THREAD

**Issue by Porkepix** [Perflyst/Twire#47]
Currently, once a stream is playing, the only way to get back to the previous screen and the application menus is to click the arrow on the stream frame.

It would be a nice addition to allow user to do the same with Android's previous button (maybe also have the slide menu on the left? No idea about that one).

**Comment by aladar42** [comment]
Additionally, this results in a state where once a stream goes offline, you can't click the back arrow anymore and the app needs to be force stopped.
