### ISSUE TITLE
Can't login with my Twitch account (TLS1.2 backport for old android)

### ISSUE THREAD

**Issue by terzag** [Perflyst/Twire#51]
Hello,
When I try to log in with my Twitch account in Twire, I get the form from Twitch and I'm then redirected to a page −which, weirdly, has no formatting− asking to allow access to the app. When I click on the button to do it, nothing happens at all. Twire doesn't appear in my Connections tab on Twitch. Other apps/services with Twitch integration I've tried work fine.

It happens both on a phone (Huawei Ice-Twist, Android 4.2.2) and a tablet (Samsung Galaxy Tab 2, Android 4.1.2).

**Comment by Perflyst** [comment]
Maybe due to old android version as login works here. Do you have a newer device to test with?

**Comment by terzag** [comment]
Unfortunately, no, that's all I have.

**Comment by terzag** [comment]
I now have another issue which may or not have the same underlying cause, so I'm not sure if I should open a new report or not. In doubt, I'll explain there.

Basically, about 4 days ago (after my initial message), Twire completely stopped being able to connect to the Twitch servers, it displays an error about them and can't even get a list of streams or categories. The weird thing is that it happens also with the official Twitch app (it displays a "network error" issue but I assume it's the same). I first thought it was an issue on the servers, so I've waited, but I doubt that it would last for 4 days, so I'm assuming that it's on my side.

As a developer having access to the API, do you know if Twitch changed something in the auth process a few days ago? Doing a bit of research, I've come across messages mentioning dropping TLSv1 support but I'm not sure if the time frame matches; or maybe it's older but they changed again recently to a newer implementation of TLS?

**Comment by Perflyst** [comment]
Looks like, they only support TLS 1.2 at the moment. Can you access https://www.twitch.tv? I dont think you can.

**Comment by terzag** [comment]
I can't access it using the stock browser of my tablet (it probably hasn't been updated since 2012) but I can using Firefox. Watching streams is barely usable but access works.

Do you have any idea if they changed something specifically 6 days ago or so in their auth system (I mean, did they announce something to devs)?

**Comment by Perflyst** [comment]
As far as I can see this could be implemented, yes.

**Comment by AnyoeDove** [comment]
found some similar discussion in NewPipe-legacy

https://github.com/TeamNewPipe/NewPipe-legacy/issues/30
