### ISSUE TITLE
Background/picture-in-picture

### ISSUE THREAD

**Issue by fefo-dev** [Perflyst/Twire#54]
As of now in Android 9 (LineageOS) I couldn't watch/listen a stream in the background outside of split-screen. Is it possible to keep the stream running in the back, and even maybe add a floating window mode?

Dunno if it's easy to implement the default option from Android, used by YouTube and a few apps running fullscreen, or add a more robust choice like what Newpipe does. The license seems compatible, the code however I have no idea.

**Comment by Perflyst** [comment]
Duplicate of  #20

**Comment by PeterDaveHello** [comment]
@Perflyst just want to confirm that is the background player support also part of #20? Thanks.
