### ISSUE TITLE
[1.9.6] Can't change aspect ratio

### ISSUE THREAD

**Issue by saasasasasa** [Perflyst/Twire#56]
I have a phone with 18:9 screen aspect ratio and with the newest version of Twire 1.9.6 if the stream is in 16:9 ratio then it's zooming in and top and bottom pixels are not visible.

In 1.9.2 version it's fine. 16:9 ratio stream is showing in original size with black bars on the sides.

It would be nice to have a screen gesture to stretch and unstretch the aspect ratio and/or something in the settings to change it.

**Comment by seyretbiz** [comment]
You can paid support me  ?
I need 3 support and itis very simple but i dont understund

How work you https://invidio.us video page data but my server not
i want add invidous my html template (you help me how adding my code )
How using a lot of domain other template one server
You agre i now sent you paid you paypal account
