### ISSUE TITLE
Stream is no longer Live

### ISSUE THREAD

**Issue by west89** [Perflyst/Twire#59]
Playback is not possible but via the Twitch page gent it.
![Screenshot_20191116-123237](https://user-images.githubusercontent.com/42120960/68992799-5f7efc00-0868-11ea-8dea-7750ec070923.jpg)

**Comment by Yamakaky** [comment]
Same problem, being connected or not doesn't seem to make a difference.

**Comment by Disqu3-mirOir-qt** [comment]
same too

**Comment by Perflyst** [comment]
Appears to be same bug as in upstream version, https://github.com/SebastianRask/Pocket-Plays-for-Twitch/commit/04d7c8a875adbad2f588a2e706a7b4e2c8a7409f needs to be applied here too

**Comment by west89** [comment]
So a bug in the app ??

**Comment by NilsIrl** [comment]
> So a bug in the app ??
> Even if I am logged out it is not.

It's twitch blocking certain client IDs.

**Comment by west89** [comment]
Pocket Plays-for-Twitch



> > So a bug in the app ??
> > Even if I am logged out it is not.
> 
> It's twitch blocking certain client IDs.

when will there be an update to F-Droid?
Pocket plays for twitch fixed it

**Comment by Perflyst** [comment]
Yes, the release is already tagged: https://github.com/Perflyst/Twire/releases/tag/v1.9.7
Should be available in F-Droid automatically in a few days

**Comment by west89** [comment]
The update is free but it does not work.

**Comment by NilsIrl** [comment]
> The update is free

I don't know what you are referring to by "free" but for me it doesn't work as well

**Comment by west89** [comment]
> > The update is free
> 
> I don't know what you are referring to by "free" but for me it doesn't work as well

@Perflyst has written that the update in F-Droid will release in the next few days.
