### ISSUE TITLE
"Stream no longer live" in version 1.9.7

### ISSUE THREAD

**Issue by shkmaru** [Perflyst/Twire#63]
The error "Stream no longer live" still happens in the version 1.9.7.

**Comment by west89** [comment]
> The error "Stream no longer live" still happens in the version 1.9.7.

Pocket Plays for Twitch 1.8.9 Play Store has been around since the last update.

**Comment by shkmaru** [comment]
They are very similar. Is one a rip-off of the other?

**Comment by west89** [comment]
> They are very similar. Is one a rip-off of the other?

![Screenshot_20191122-021750__01](https://user-images.githubusercontent.com/42120960/69390105-73928580-0cce-11ea-9596-031c3d0dbb80.jpg)

What's different about Twire from F-Droid can only be said by the creator

**Comment by Perflyst** [comment]
> What's different about Twire from F-Droid can only be said by the creator

Twire is a fork of Pocket Plays without proprietary libraries, see discussion in https://github.com/Perflyst/Twire/issues/2

**Comment by DPTJKKVH** [comment]
I looked at the code and your patch to hardcode `kimne78kx3ncx6brgo4mv6wki5h1ko` as the clientID should have fixed the issue with Twitch recently changing the api key.

Do you have any idea what could cause this issue?

**Comment by DPTJKKVH** [comment]
Just a quick confirmation that this bug is, as expected, fixed with the new release. Thanks again to @samfun123 for providing the fix and to @Perflyst for reviewing and releasing a fixed version.
