### ISSUE TITLE
"My Streams" preview image doesn't update

### ISSUE THREAD

**Issue by LukasThyWalls** [Perflyst/Twire#82]
Hello

In "My Streams" tab, when i see the list of live streams, the preview image doesn't update. It took one when i first log in, but since then didn't change although the channel went offline and online again, with other game, or different streamers if the channel have more than one, but the preview image is the same than the first time.

If i update the 'My Streams' tab swiping down, it doesn't change the previews.

I cleared the app cache (not the data) and then it take another actual preview image, but it didn't take newer ones at any moment, it got stuck with the first.

It happens since 2.0.1 (With 2.0.0 i had the issue with the login, so i can't know if the problem was there too, because i haven't the "My Streams" tab then)

Thanks.

**Comment by LukasThyWalls** [comment]
Thanks.

I entered to see if there is a new releases with this, but there isn't, anyway this isn't a big issue with the app.

However, i see the fix description and the code snippet, will it update every 5 minutes whatever you are doing in the app or will it update if when you refresh the list (when you enter the "My Streams" tab, or swipe down there) and the previews are older than 5 minutes? (The first one doesn't seems very efficent...) It could be great too if it forces a new preview if the title or game has changed since the last preview, although maybe it could be more difficult to make it work in the App.

Anyway, thanks!

**Comment by samfun123** [comment]
Basically every 5 minutes the preview image won't be read from cache. The problem was that the preview image URL doesn't change so it was basically being cached forever. So it'll do the second one.

The My Streams tab doesn't refresh unless it doesn't have the data already. Like switching to it from another tab or the app isn't running in the background and you open up the app.

**Comment by LukasThyWalls** [comment]
Thank you for the clarification!

**Comment by Perflyst** [comment]
I just switched to a bit different versioning, https://github.com/Perflyst/Twire/commit/1942ad0179f6a2a260a8c49d02fac3964e1ad666, therefore new updates can now be released faster without reaching 3.0 too fast

**Comment by LukasThyWalls** [comment]
It's been a while since this issue is fixed, bit i need to point out something.

It's less issue than the original one, but for sure related, the preview image is fine and working, but when you tap to load a live stream, there is a second or two trying to load it until shows the video, meanwhile Twire shows a preview image that should be the same one you see in the list, but it is not, in fact normally is a old one like the one used to be when this issue isn't fixed.

When you load a VOD, the "load preview" is the same as the "list preview" always.

It is something you see a second or two as much, and for sure is not important, but it's there

Sorry but i need to point out this.

**Comment by samfun123** [comment]
@LukasThyWalls In case GitHub doesn't give a notification about this, I believe the preview transition image should now be consistent.

**Comment by LukasThyWalls** [comment]
No, @samfun123, github didn't give me a notification about that.
I will test it when there is a new build.
