### ISSUE TITLE
App Crashing on opening any stream

### ISSUE THREAD

**Issue by FireMasterK** [Perflyst/Twire#86]
Crash log: https://del.dog/ephozamume
The app was working fine before this.

**Comment by Wolf-Rayet** [comment]
Mine was working before update. Open any stream would instant crash. 

Possible fix: Uninstall app. Reinstall. 

Current: Working fine now on latest and able to watch streams

**Comment by digital-mystik** [comment]
This happens occasionally for me as well; I have to clear app data and reconfigure to fix the issue. It will work for a while and then start crashing on subsequent sessions.

**Comment by Wolf-Rayet** [comment]
Reinstalling only "fixed" my issue for 5-6 days until the error started happening again last night. Once I select a stream, instant crash.

**Comment by weinland** [comment]
Same issue here on LineageOS 17.1 with Twire 2.512.
Reinstalling and downgrading did not work.
The app crashes when opening a stream while being logged in. Opening streams without being logged in works.
