### ISSUE TITLE
Chat visible when in landscape mode

### ISSUE THREAD

**Issue by m1ga** [Perflyst/Twire#87]
with the latest update 2.513 the chat is now visible when you hold your phone in landscape mode:
![Screenshot_20200510-114852](https://user-images.githubusercontent.com/4334997/81495961-684f0880-92b4-11ea-8fbf-774c71ad0b5c.png)
Before the update it was covered/cut away.

Pixel 4, Android 10

**Comment by LukasThyWalls** [comment]
I can confirm this too. It was not presented in 2.512.

Maybe related with "#d45bf2b Reduce the amount of overdraw" with FHD+ screens (Wider than FullHD resolutions).

**Comment by akashpal-21** [comment]
Can confirm this too. 
X01BD, Android 9

Downgrading for now.
