### ISSUE TITLE
Twire never connect to the chat

### ISSUE THREAD

**Issue by TheFrenchGhosty** [Perflyst/Twire#89]
Twire isn't able to connect to the chat, it just hang with "Connecting to chat..." 

Running F-Droid version 2.513 (so it was maybe fixed with https://github.com/Perflyst/Twire/commit/050620447d77856d6f13b873054dfeb25b987728 )

I am using a Twitch account in it.

**Comment by samfun123** [comment]
Are you still experiencing this issue or was it resolved by logging out and back in like in #90?

**Comment by TheFrenchGhosty** [comment]
Looks like it also fixed it yeah. That's a good thing I guess.
