### ISSUE TITLE
"My games" trigger a server error

### ISSUE THREAD

**Issue by TheFrenchGhosty** [Perflyst/Twire#90]
When opening "My games", "Oops, Twitch's servers don't seem to be responding. Refresh?" is displayed, and nothing is loaded.

Running F-Droid version 2.513.

I am using a Twitch account in it.

**Comment by samfun123** [comment]
Could you try logging out and logging back in? For some reason this seems to fix issues like this for people. I wish I could reproduce this issue but doesn't happen for me.

**Comment by TheFrenchGhosty** [comment]
Mmh it's weird but it fixed the issue yeah.

**Comment by samfun123** [comment]
I'm not sure really. I think there's an API that twitch provides that allows me to check if a login is still valid, maybe that would detect this issue and then I could automatically log the user out and ask them to log back in.

**Comment by samfun123** [comment]
I'm going to close this issue as the next version of Twire includes something that should validate your login.
