### ISSUE TITLE
[Feature Request] Apply background on stream player frontmost layer

### ISSUE THREAD

**Issue by hunkjazz** [Perflyst/Twire#98]
When the user is watching to a streamer and taps the video (e.g. to see viewer count), it's barely possible to see revealed options.

This is a lack of contrast issue, I'm afraid.

It can be solved by applying a fairly transparent black background on this frontmost layer.

**Comment by hunkjazz** [comment]
Live thumbnails are also lacking contrast.

**Comment by fefo-dev** [comment]
Against white backgrounds is almost impossible to distinguish the controls. YouTube app does the grey layer too, but a simple drop shadow on the buttons would fix it.

**Comment by hunkjazz** [comment]
@fefo-dev 

I think any video service includes this feature.

> but a simple drop shadow on the buttons would fix it

Yeah, but may get weird depending on the button shape.

Using a nearly transparent background is what's best in terms of UX and it's LOT simple to implement. Too bad I can't help!
